name: Deploy Documentation
on:
  push:
    branches:
      - fix/deploy-docs
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - shell: bash
        run: |
          echo "1.0.`date +%s`" > version.txt
      - name: Upload version artifact
        uses: actions/upload-artifact@v2
        with:
          name: version
          path: version.txt
      - name: Get the version
        id: get_version
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_OUTPUT
      - name: Build and publish docker image wiht docs for SAP CC
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: docs-storefrontcloud-io/v2-sdk-magento2:${{ steps.get_version.outputs.VERSION }}
          registry: registry.storefrontcloud.io
          username: ${{ secrets.DOCS_CLOUD_USERNAME }}
          password: ${{ secrets.DOCS_CLOUD_PASSWORD }}
          workdir: .
          dockerfile: ./.vuestorefrontcloud/docker/docs/Dockerfile
          buildoptions: "--compress"
          buildargs: NPM_EMAIL,NPM_PASS,NPM_USER,NPM_REGISTRY
        env:
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_PASS: ${{ secrets.NPM_PASS }}
          NPM_USER: ${{ secrets.NPM_USER }}
          NPM_REGISTRY: "https://registrynpm.storefrontcloud.io"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download version artifact
        uses: actions/download-artifact@v2
        with:
          name: version
      - name: Get the version
        id: get_version
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_OUTPUT
      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          target_url: https://docs.europe-west1.gcp.storefrontcloud.io/sdk-magento2
          environment: production
          initial_status: in_progress
      - name: Deploy on docs.europe-west1.gcp.storefrontcloud.io/sdk-magento2
        id: publish
        uses: vuestorefront/publish-docs-action@main
        with:
          user-id: ${{ secrets.DOCS_CLOUD_USERNAME }}
          api-key: ${{ secrets.DOCS_CLOUD_PASSWORD }}
          name: "docs-v2-sdk-magento2"
          tag: "${{ steps.get_version.outputs.VERSION }}"
          image: "registry.storefrontcloud.io/docs-storefrontcloud-io/v2-sdk-magento2"
          path: "/sdk-magento2"
          port: "80"
          has-base-path: true
      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: https://docs.europe-west1.gcp.storefrontcloud.io/sdk-magento2
          state: "success"
          description: Congratulations! The deploy is done.
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: https://docs.europe-west1.gcp.storefrontcloud.io/sdk-magento2
          description: Unfortunately, the instance hasn't been updated.
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
