- uses: actions/checkout@v1
          - name: Extract branch name
          shell: bash
          run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          id: extract_branch
          - name: Extract tag name
            shell: bash
            run: |
              branch=${{ steps.extract_branch.outputs.branch }}
              echo "##[set-output name=tag;]$(echo ${branch#release/})"
            id: extract_tag
          - uses: yanamura/git-flow-merge-action@v1
            with:
              ### GITHUB_TOKEN.(required)
              github_token: ${{ secrets.GITHUB_TOKEN }}

              ### branch name which merged to develop and master branch.(required)
              ### ex. release/1.1.0, hotfix_branch
              branch: ${{ steps.extract_branch.outputs.branch }}

              ### develop branch name. default: develop (optional).
              develop_branch: 'develop'

              ### main branch name. default: master (optional).
              main_branch: 'master'

              ### tag name which tagged to master.(optional)
              ### ex. v1.1.0
              tag: v${{ steps.extract_tag.outputs.tag }}
