name: Gitflow Merge
on:
  pull_request:
    branches:
      - release/*
      - master
      - develop
    types: [ opened, ready_for_review, edited, synchronize ]
jobs:
  automerge:
    if: contains(github.event.pull_request.labels.*.name, 'gitflow') && contains(${{ secrets.PR_ACTION_AUTHORS }}, github.actor)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Extract branch name
        uses: mdecoleman/pr-branch-name@1.0.0
        id: extract_branch
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: yanamura/git-flow-merge-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.extract_branch.outputs.branch }}
          develop_branch: 'develop'
          main_branch: 'master'
          tag: ${{ steps.extract_tag.outputs.tag }}
