name: Gitflow Merge & Publish Packages on NPM
on:
  pull_request:
    branches:
      - release/*
      - master
      - develop
jobs:
  publishing:
    name: Package Publishing
    if: contains(github.event.pull_request.labels.*.name, 'release') && contains(${{ secrets.PR_ACTION_AUTHORS }}, github.actor)
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org/"
          scope: "@vue-storefront"
      - run: echo "" >> .npmrc && echo "@vue-storefront:registry=https://registry.npmjs.org/" >> .npmrc
      - run: yarn
      - run: yarn build:api-client
      - run: yarn build:composables
      - run: yarn publish:packages "${{ join(github.event.pull_request.labels.*.name, '|') }}" "$NODE_AUTH_TOKEN"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  automerge:
    needs: publishing
    name: GitFlow AutoMerge
    if: contains(github.event.pull_request.labels.*.name, 'release') && contains(${{ secrets.PR_ACTION_AUTHORS }}, github.actor)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Extract branch name
        uses: mdecoleman/pr-branch-name@1.0.0
        id: extract_branch
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        shell: bash
        run: |
          branch=${{ steps.extract_branch.outputs.branch }}
          echo "##[set-output name=tag;]$(echo ${branch#release/})"
        id: extract_tag

      - name: Gitflow AutoMerge Branches
        uses: yanamura/git-flow-merge-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.extract_branch.outputs.branch }}
          develop_branch: "develop"
          main_branch: "master"
          tag: ${{ steps.extract_tag.outputs.tag }}
